language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=test
services:
  - mongodb
install:
  - npm install
before_script:
  - grunt e2e:server &
script:
  - grunt test:server && grunt karma:unit && grunt e2e:test
